//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC2_Lobby_Notifier.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC2_Lobby_Notifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ABANDONED.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new map.
        /// </summary>
        public static string AddMapButtonContent {
            get {
                return ResourceManager.GetString("AddMapButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new arcade map to table.
        /// </summary>
        public static string AddMapButtonToolTip {
            get {
                return ResourceManager.GetString("AddMapButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t get data. Please check Internet connection.
        ///.
        /// </summary>
        public static string ConnectionIsLostMessage {
            get {
                return ResourceManager.GetString("ConnectionIsLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection fully restored.
        ///.
        /// </summary>
        public static string ConnectionRestoredMessage {
            get {
                return ResourceManager.GetString("ConnectionRestoredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable search.
        /// </summary>
        public static string DisableSearch {
            get {
                return ResourceManager.GetString("DisableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable search.
        /// </summary>
        public static string EnableSearch {
            get {
                return ResourceManager.GetString("EnableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host: .
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of map which you want to add.
        /// </summary>
        public static string InpuBoxToolTip {
            get {
                return ResourceManager.GetString("InpuBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobby was abandoned at: .
        /// </summary>
        public static string LobbyAbandonedMessage {
            get {
                return ResourceManager.GetString("LobbyAbandonedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobby was started at: .
        /// </summary>
        public static string LobbyStartedMessage {
            get {
                return ResourceManager.GetString("LobbyStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map &quot;newMap&quot; successfully added to the table.
        ///.
        /// </summary>
        public static string MapAddedMessage {
            get {
                return ResourceManager.GetString("MapAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map &quot;newMap&quot; is already exists on the table.
        ///.
        /// </summary>
        public static string MapAlreadyExistMessage {
            get {
                return ResourceManager.GetString("MapAlreadyExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map &quot;newMap&quot; doesn&apos;t exist in StarCraft 2.
        ///.
        /// </summary>
        public static string MapNotExistMessage {
            get {
                return ResourceManager.GetString("MapNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string MapsNamesColumn {
            get {
                return ResourceManager.GetString("MapsNamesColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of StarCraft 2 map.
        /// </summary>
        public static string MapsNamesColumnToolTip {
            get {
                return ResourceManager.GetString("MapsNamesColumnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete selected maps.
        /// </summary>
        public static string MapsNamesContextMenuDeleteSlectedMaps {
            get {
                return ResourceManager.GetString("MapsNamesContextMenuDeleteSlectedMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open EU map on StarCraft II Arcade.
        /// </summary>
        public static string MapsNamesContextMenuOpenLinkEU {
            get {
                return ResourceManager.GetString("MapsNamesContextMenuOpenLinkEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open US map on StarCraft II Arcade.
        /// </summary>
        public static string MapsNamesContextMenuOpenLinkUS {
            get {
                return ResourceManager.GetString("MapsNamesContextMenuOpenLinkUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change EU search status.
        /// </summary>
        public static string MapsNamesContextMenuSearchOnEU {
            get {
                return ResourceManager.GetString("MapsNamesContextMenuSearchOnEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change US search status.
        /// </summary>
        public static string MapsNamesContextMenuSearchOnUS {
            get {
                return ResourceManager.GetString("MapsNamesContextMenuSearchOnUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OPENED.
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players in lobby.
        /// </summary>
        public static string PlayersInLobby {
            get {
                return ResourceManager.GetString("PlayersInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remaining:.
        /// </summary>
        public static string Remaining {
            get {
                return ResourceManager.GetString("Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobbies search disabled.
        ///.
        /// </summary>
        public static string SearchDisabledMessage {
            get {
                return ResourceManager.GetString("SearchDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobbies search enabled.
        ///.
        /// </summary>
        public static string SearchEnabledMessage {
            get {
                return ResourceManager.GetString("SearchEnabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map search status on European server.
        /// </summary>
        public static string SearchOnEUColumnToolTip {
            get {
                return ResourceManager.GetString("SearchOnEUColumnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map search status on American server.
        /// </summary>
        public static string SearchOnUSColumnToolTip {
            get {
                return ResourceManager.GetString("SearchOnUSColumnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show main window.
        /// </summary>
        public static string ShowMainWindow {
            get {
                return ResourceManager.GetString("ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StarCraft II Arcade doesn&apos;t work. Please try again later.
        ///.
        /// </summary>
        public static string SiteDoesntWorkMessage {
            get {
                return ResourceManager.GetString("SiteDoesntWorkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StarCraft II Arcade doesn&apos;t work on EU server. Search work only on US server.
        ///.
        /// </summary>
        public static string SiteDoesntWorkOnEUMessage {
            get {
                return ResourceManager.GetString("SiteDoesntWorkOnEUMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StarCraft II Arcade doesn&apos;t work on US server. EU server work only.
        ///.
        /// </summary>
        public static string SiteDoesntWorkOnUSMessage {
            get {
                return ResourceManager.GetString("SiteDoesntWorkOnUSMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STARTED.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title: .
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UNKNOWN.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobby was infected by zerg swarm at: .
        /// </summary>
        public static string UnknownEnd1 {
            get {
                return ResourceManager.GetString("UnknownEnd1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobby has returned to the Void at: .
        /// </summary>
        public static string UnknownEnd2 {
            get {
                return ResourceManager.GetString("UnknownEnd2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lobby was blown to hell at: .
        /// </summary>
        public static string UnknownEnd3 {
            get {
                return ResourceManager.GetString("UnknownEnd3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must first enter name of the map.
        ///.
        /// </summary>
        public static string UserNotEnteredMapNameMessage {
            get {
                return ResourceManager.GetString("UserNotEnteredMapNameMessage", resourceCulture);
            }
        }
    }
}
